build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules set this to false
  excludes: "build"

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexMethod:
    active: true
    threshold: 15
    ignoreSingleExpression: false
    ignoreSimpleDefinition: false
    ignoreNestLoops: false
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 100
  LongParameterList:
    active: true
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludeClassPattern: '.*Test'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '.*Test'

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  UnusedImports:
    active: true
  WildcardImport:
    active: true
    excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*']
